use crate::parser::Request;
use std::collections::BTreeMap;

use super::{format, identifiers, model_catalog, typing};

/// Builds full `schema.ts` file content.
///
/// Generates sections in fixed order:
/// 1) model aliases, 2) `Schemas`, 3) `Endpoints`.
///
/// Example:
/// `export type User = {...};`
/// `export interface Schemas {...}`
/// `export interface Endpoints {...}`
pub fn build_schema_file(
    requests: &[Request],
    models: &BTreeMap<String, crate::parser::SchemaType>,
) -> String {
    let catalog = model_catalog::build_model_catalog(requests, models);
    let type_names = identifiers::build_type_names(&catalog.names);
    let methods = collect_methods(requests);

    let mut out = String::new();
    out.push_str("// This file is generated by kayto. Do not edit manually.\n\n");
    add_model_types(&mut out, &catalog, &type_names);
    add_schemas(&mut out, &catalog, &type_names);
    add_endpoints(&mut out, &methods);
    out
}

/// Adds top-level model type aliases used by schema registry and endpoints.
///
/// Example:
/// `export type User = { "id": string; };`
fn add_model_types(
    out: &mut String,
    catalog: &model_catalog::ModelCatalog,
    type_names: &BTreeMap<String, String>,
) {
    for model_name in &catalog.names {
        let type_name = type_names
            .get(model_name)
            .expect("type identifier must exist for each model name");

        let ts_type = match catalog.definitions.get(model_name) {
            Some(schema_type) => typing::schema_type(schema_type),
            None => "unknown".to_string(),
        };

        out.push_str(&format!("export type {type_name} = {ts_type};\n\n"));
    }
}

/// Adds `Schemas` interface that maps source schema keys to TS aliases.
///
/// Example:
/// `export interface Schemas { "user": User; }`
fn add_schemas(
    out: &mut String,
    catalog: &model_catalog::ModelCatalog,
    type_names: &BTreeMap<String, String>,
) {
    out.push_str("export interface Schemas {\n");
    for model_name in &catalog.names {
        let type_name = type_names
            .get(model_name)
            .expect("type identifier must exist for each model name");
        out.push_str(&format!("  {}: {type_name};\n", format::quote(model_name)));
    }
    out.push_str("}\n\n");
}

/// Adds `Endpoints` interface grouped by HTTP method.
///
/// Example:
/// `export interface Endpoints { "get": { "/users": {...}; }; }`
fn add_endpoints(out: &mut String, methods: &BTreeMap<String, BTreeMap<String, &Request>>) {
    out.push_str("export interface Endpoints {\n");
    for (method, path_map) in methods {
        out.push_str(&format!("  {}: {{\n", format::quote(method)));
        for (path, req) in path_map {
            add_endpoint(out, method, path, req);
        }
        out.push_str("  };\n");
    }
    out.push_str("}\n");
}

/// Adds one endpoint metadata entry for a single method + path.
///
/// Example:
/// `"/users": { path: "/users"; method: "get"; params?: never; ... };`
fn add_endpoint(out: &mut String, method: &str, path: &str, req: &Request) {
    out.push_str(&format!("    {}: {{\n", format::quote(path)));
    out.push_str(&format!("      path: {};\n", format::quote(&req.path)));
    out.push_str(&format!("      method: {};\n", format::quote(method)));

    if let Some(operation_id) = &req.operation_id {
        out.push_str(&format!(
            "      operationId: {};\n",
            format::quote(operation_id)
        ));
    }

    match typing::params_type(req) {
        Some(params_type) => out.push_str(&format!(
            "      params: {};\n",
            format::indent_multiline(&params_type, "      ")
        )),
        None => out.push_str("      params?: never;\n"),
    }

    match req.body.as_ref() {
        Some(body) => {
            let body_type = typing::response_type(body);
            out.push_str(&format!(
                "      body: {};\n",
                format::indent_multiline(&body_type, "      ")
            ));
        }
        None => out.push_str("      body?: never;\n"),
    }

    match typing::responses_type(req) {
        Some(responses_type) => out.push_str(&format!(
            "      responses: {};\n",
            format::indent_multiline(&responses_type, "      ")
        )),
        None => out.push_str("      responses?: never;\n"),
    }

    out.push_str("    };\n");
}

/// Groups parsed requests by HTTP method and then by path for deterministic output.
fn collect_methods(requests: &[Request]) -> BTreeMap<String, BTreeMap<String, &Request>> {
    let mut methods: BTreeMap<String, BTreeMap<String, &Request>> = BTreeMap::new();
    for req in requests {
        methods
            .entry(req.method.to_lowercase())
            .or_default()
            .insert(req.path.clone(), req);
    }
    methods
}
