use crate::parser::{ObjectType, PrimitiveType, Request, SchemaType};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashSet};

use super::{format, identifiers, model_catalog, typing};

/// Builds full `schema.dart` file content.
///
/// Generates sections in fixed order:
/// 1) model aliases/classes, 2) `Schemas`, 3) `HttpMethod`, 4) `Endpoints`.
///
/// Example:
/// `typedef User = ...;`
/// `abstract final class Schemas {...}`
/// `abstract final class Endpoints {...}`
pub fn build_schema_file(
    requests: &[Request],
    models: &BTreeMap<String, crate::parser::SchemaType>,
) -> String {
    let model_data = model_catalog::build_model_catalog(requests, models);
    let identifiers = identifiers::build_type_names(&model_data.names);
    let methods = collect_methods(requests);

    let mut out = String::new();
    out.push_str("// This file is generated by kayto. Do not edit manually.\n\n");
    add_model_types(&mut out, &model_data, &identifiers);
    add_schemas_namespace(&mut out, &model_data, &identifiers);
    add_http_method_enum(&mut out, &methods);
    add_endpoints_namespace(&mut out, &methods, &identifiers);
    out
}

/// Adds top-level model declarations (`typedef`, class, enum) for schemas.
///
/// Example:
/// `typedef UserId = String;`
/// `class User {...}`
/// `enum Status {...}`
fn add_model_types(
    out: &mut String,
    model_data: &model_catalog::ModelCatalog,
    identifiers: &BTreeMap<String, String>,
) {
    for model_name in &model_data.names {
        let ident = identifiers
            .get(model_name)
            .expect("type identifier must exist for each model name");

        match model_data.definitions.get(model_name) {
            Some(SchemaType::Object(obj)) => {
                add_object_model_class(out, ident, &obj, identifiers);
                out.push('\n');
            }
            Some(SchemaType::Primitive(primitive))
                if primitive
                    .enum_values
                    .as_ref()
                    .is_some_and(|values| !values.is_empty())
                    && matches!(primitive.kind, PrimitiveType::String) =>
            {
                if add_string_enum_model(
                    out,
                    ident,
                    primitive.enum_values.as_ref().expect("checked above"),
                ) {
                    out.push('\n');
                } else {
                    let dart_type =
                        typing::schema_type(&SchemaType::Primitive(primitive.clone()), identifiers);
                    out.push_str(&format!("typedef {ident} = {dart_type};\n\n"));
                }
            }
            Some(schema_type) => {
                let dart_type = typing::schema_type(schema_type, identifiers);
                out.push_str(&format!("typedef {ident} = {dart_type};\n\n"));
            }
            None => out.push_str(&format!("typedef {ident} = Object?;\n\n")),
        }
    }
}

/// Adds `Schemas` namespace with typed schema getters.
///
/// Example:
/// `abstract final class Schemas { static User? get user => null; }`
fn add_schemas_namespace(
    out: &mut String,
    model_data: &model_catalog::ModelCatalog,
    identifiers: &BTreeMap<String, String>,
) {
    out.push_str("abstract final class Schemas {\n");

    let getter_names = build_schema_getter_names(&model_data.names, identifiers);
    if !getter_names.is_empty() {
        out.push_str("  // Autocomplete-friendly typed schema references.\n");
        for (model_name, getter_name) in getter_names {
            let ident = identifiers
                .get(&model_name)
                .expect("type identifier must exist for each model name");
            out.push_str(&format!("  static {ident}? get {getter_name} => null;\n"));
        }
    }

    out.push_str("}\n\n");
}

/// Adds HTTP method enum used by endpoint contracts.
///
/// Example:
/// `enum HttpMethod { get, post }`
fn add_http_method_enum(out: &mut String, methods: &BTreeMap<String, BTreeMap<String, &Request>>) {
    out.push_str("enum HttpMethod {\n");
    for method in methods.keys() {
        out.push_str(&format!("  {method},\n"));
    }
    out.push_str("}\n\n");
}

/// Adds root `Endpoints` namespace grouped by HTTP method.
///
/// Example:
/// `abstract final class Endpoints { static const get = EndpointsGet(); }`
fn add_endpoints_namespace(
    out: &mut String,
    methods: &BTreeMap<String, BTreeMap<String, &Request>>,
    identifiers: &BTreeMap<String, String>,
) {
    add_method_endpoint_classes(out, methods, identifiers);

    out.push_str("abstract final class Endpoints {\n");
    for method in methods.keys() {
        let class_name = method_class_name(method);
        out.push_str(&format!("  static const {method} = {class_name}();\n"));
    }
    out.push_str("}\n");
}

/// Adds method-specific endpoint classes with typed getters.
///
/// Example:
/// `class EndpointsGet { EndpointGetUsers get users => _users; }`
fn add_method_endpoint_classes(
    out: &mut String,
    methods: &BTreeMap<String, BTreeMap<String, &Request>>,
    identifiers: &BTreeMap<String, String>,
) {
    for (method, path_map) in methods {
        let class_name = method_class_name(method);
        let getter_names = build_endpoint_getter_names(path_map);

        for (path, getter_name) in &getter_names {
            let req = path_map
                .get(path)
                .expect("request must exist for generated getter path");
            add_single_endpoint_contract(out, method, getter_name, req, identifiers);
        }

        out.push_str(&format!("class {class_name} {{\n"));
        out.push_str(&format!("  const {class_name}();\n\n"));
        for (path, getter_name) in &getter_names {
            let req = path_map
                .get(path)
                .expect("request must exist for generated getter path");
            let endpoint_class = endpoint_contract_name(method, getter_name);

            out.push_str(&format!(
                "  static const {endpoint_class} _{getter_name} = {endpoint_class}(\n"
            ));
            add_endpoint_fields(out, "    ", method, req, identifiers, getter_name);
            out.push_str("  );\n\n");
            out.push_str(&format!(
                "  {endpoint_class} get {getter_name} => _{getter_name};\n"
            ));
        }

        out.push_str("}\n\n");
    }
}

/// Adds constructor argument values for one endpoint constant.
///
/// Example:
/// `path: '/users', method: HttpMethod.get, bodyType: User`
fn add_endpoint_fields(
    out: &mut String,
    field_indent: &str,
    method: &str,
    req: &Request,
    identifiers: &BTreeMap<String, String>,
    getter_name: &str,
) {
    out.push_str(&format!(
        "{field_indent}path: {},\n",
        format::quote(&req.path)
    ));
    out.push_str(&format!("{field_indent}method: HttpMethod.{method},\n",));

    if let Some(operation_id) = &req.operation_id {
        out.push_str(&format!(
            "{field_indent}operationId: {},\n",
            format::quote(operation_id)
        ));
    }

    if req.params.as_ref().is_some_and(|params| !params.is_empty()) {
        let params_class = endpoint_params_name(method, getter_name);
        out.push_str(&format!("{field_indent}params: {params_class}(\n"));
        add_endpoint_params_value(
            out,
            &format!("{field_indent}  "),
            method,
            getter_name,
            req,
            identifiers,
        );
        out.push_str(&format!("{field_indent}),\n"));
    }

    if let Some(body) = req.body.as_ref() {
        let body_type = typing::response_type(body, identifiers);
        out.push_str(&format!(
            "{field_indent}bodyType: {},\n",
            type_literal_expr(&body_type)
        ));
    }

    if req
        .responses
        .as_ref()
        .is_some_and(|responses| !responses.is_empty())
    {
        let responses_class = endpoint_responses_name(method, getter_name);
        out.push_str(&format!("{field_indent}responses: {responses_class}(\n"));
        add_endpoint_responses_value(
            out,
            &format!("{field_indent}  "),
            method,
            getter_name,
            req,
            identifiers,
        );
        out.push_str(&format!("{field_indent}),\n"));
    }
}

/// Adds endpoint contract class and links params/responses contracts if present.
///
/// Example:
/// `class EndpointGetUsers { final String path; final Type? bodyType; ... }`
fn add_single_endpoint_contract(
    out: &mut String,
    method: &str,
    getter_name: &str,
    req: &Request,
    identifiers: &BTreeMap<String, String>,
) {
    let endpoint_class = endpoint_contract_name(method, getter_name);
    let params_class = endpoint_params_name(method, getter_name);
    let responses_class = endpoint_responses_name(method, getter_name);

    if req.params.as_ref().is_some_and(|params| !params.is_empty()) {
        add_endpoint_params_contract(out, method, getter_name, req, identifiers);
    }
    if req
        .responses
        .as_ref()
        .is_some_and(|responses| !responses.is_empty())
    {
        add_endpoint_responses_contract(out, method, getter_name, req, identifiers);
    }

    out.push_str(&format!("class {endpoint_class} {{\n"));
    out.push_str("  final String path;\n");
    out.push_str("  final HttpMethod method;\n");
    out.push_str("  final String? operationId;\n");
    if req.params.as_ref().is_some_and(|params| !params.is_empty()) {
        out.push_str(&format!("  final {params_class}? params;\n"));
    } else {
        out.push_str("  final Never? params;\n");
    }
    out.push_str("  final Type? bodyType;\n");
    if req
        .responses
        .as_ref()
        .is_some_and(|responses| !responses.is_empty())
    {
        out.push_str(&format!("  final {responses_class}? responses;\n\n"));
    } else {
        out.push_str("  final Never? responses;\n\n");
    }

    out.push_str(&format!("  const {endpoint_class}({{\n"));
    out.push_str("    required this.path,\n");
    out.push_str("    required this.method,\n");
    out.push_str("    this.operationId,\n");
    out.push_str("    this.params,\n");
    out.push_str("    this.bodyType,\n");
    out.push_str("    this.responses,\n");
    out.push_str("  });\n");
    out.push_str("}\n\n");
}

/// Adds params contract classes for an endpoint (`...Params` and per-location classes).
///
/// Example:
/// `class EndpointGetUsersParams { final EndpointGetUsersParamsQuery? query; }`
fn add_endpoint_params_contract(
    out: &mut String,
    method: &str,
    getter_name: &str,
    req: &Request,
    identifiers: &BTreeMap<String, String>,
) {
    let Some(params) = req.params.as_ref() else {
        return;
    };

    let mut by_location: BTreeMap<String, Vec<&crate::parser::ParsedParameter>> = BTreeMap::new();
    for param in params {
        let location = param
            .location
            .as_deref()
            .unwrap_or("other")
            .to_ascii_lowercase();
        by_location.entry(location).or_default().push(param);
    }

    let params_class = endpoint_params_name(method, getter_name);
    out.push_str(&format!("class {params_class} {{\n"));
    for location in by_location.keys() {
        let location_class = endpoint_params_location_name(method, getter_name, location);
        out.push_str(&format!(
            "  final {location_class}? {};\n",
            sanitize_endpoint_getter_name(location)
        ));
    }
    out.push('\n');
    out.push_str(&format!("  const {params_class}({{\n"));
    for location in by_location.keys() {
        out.push_str(&format!(
            "    this.{},\n",
            sanitize_endpoint_getter_name(location)
        ));
    }
    out.push_str("  });\n");
    out.push_str("}\n\n");

    for (location, mut location_params) in by_location {
        location_params.sort_by(|a, b| a.name.cmp(&b.name));
        let location_class = endpoint_params_location_name(method, getter_name, &location);
        out.push_str(&format!("class {location_class} {{\n"));
        for param in &location_params {
            let field_name = sanitize_endpoint_getter_name(&param.name);
            let mut ty = param
                .schema_type
                .as_ref()
                .map(|schema| typing::schema_type(schema, identifiers))
                .unwrap_or_else(|| "Object?".to_string());
            ty = ensure_nullable_type(&ty);
            out.push_str(&format!("  final {ty} {field_name};\n"));
        }
        out.push('\n');
        out.push_str(&format!("  const {location_class}({{\n"));
        for param in &location_params {
            let field_name = sanitize_endpoint_getter_name(&param.name);
            out.push_str(&format!("    this.{field_name},\n"));
        }
        out.push_str("  });\n");
        out.push_str("}\n\n");
    }
}

/// Adds default `null` values for endpoint params object.
///
/// Example:
/// `query: EndpointGetUsersParamsQuery(id: null,),`
fn add_endpoint_params_value(
    out: &mut String,
    indent: &str,
    method: &str,
    getter_name: &str,
    req: &Request,
    _identifiers: &BTreeMap<String, String>,
) {
    let Some(params) = req.params.as_ref() else {
        return;
    };

    let mut by_location: BTreeMap<String, Vec<&crate::parser::ParsedParameter>> = BTreeMap::new();
    for param in params {
        let location = param
            .location
            .as_deref()
            .unwrap_or("other")
            .to_ascii_lowercase();
        by_location.entry(location).or_default().push(param);
    }

    for (location, mut location_params) in by_location {
        location_params.sort_by(|a, b| a.name.cmp(&b.name));
        let location_field = sanitize_endpoint_getter_name(&location);
        let location_class = endpoint_params_location_name(method, getter_name, &location);
        out.push_str(&format!("{indent}{location_field}: {location_class}(\n"));
        for param in location_params {
            let field_name = sanitize_endpoint_getter_name(&param.name);
            out.push_str(&format!("{indent}  {field_name}: null,\n"));
        }
        out.push_str(&format!("{indent}),\n"));
    }
}

/// Adds responses contract class for an endpoint.
///
/// Example:
/// `class EndpointGetUsersResponses { final User? s200; }`
fn add_endpoint_responses_contract(
    out: &mut String,
    method: &str,
    getter_name: &str,
    req: &Request,
    identifiers: &BTreeMap<String, String>,
) {
    let Some(responses) = req.responses.as_ref() else {
        return;
    };

    let responses_class = endpoint_responses_name(method, getter_name);
    out.push_str(&format!("class {responses_class} {{\n"));
    for (status, parsed_response) in responses {
        let ty = typing::response_type(parsed_response, identifiers);
        out.push_str(&format!(
            "  final {} {};\n",
            ensure_nullable_type(&ty),
            status_field_name(*status)
        ));
    }
    out.push('\n');
    out.push_str(&format!("  const {responses_class}({{\n"));
    for status in responses.keys() {
        out.push_str(&format!("    this.{},\n", status_field_name(*status)));
    }
    out.push_str("  });\n");
    out.push_str("}\n\n");
}

/// Adds default `null` values for endpoint responses object.
///
/// Example:
/// `s200: null,`
fn add_endpoint_responses_value(
    out: &mut String,
    indent: &str,
    _method: &str,
    _getter_name: &str,
    req: &Request,
    identifiers: &BTreeMap<String, String>,
) {
    let Some(responses) = req.responses.as_ref() else {
        return;
    };

    for (status, parsed_response) in responses {
        let _ty = typing::response_type(parsed_response, identifiers);
        out.push_str(&format!("{indent}{}: null,\n", status_field_name(*status)));
    }
}

fn endpoint_contract_name(method: &str, getter_name: &str) -> String {
    format!(
        "Endpoint{}{}",
        upper_camel(method),
        upper_camel(getter_name)
    )
}

fn endpoint_params_name(method: &str, getter_name: &str) -> String {
    format!("{}Params", endpoint_contract_name(method, getter_name))
}

fn endpoint_responses_name(method: &str, getter_name: &str) -> String {
    format!("{}Responses", endpoint_contract_name(method, getter_name))
}

fn endpoint_params_location_name(method: &str, getter_name: &str, location: &str) -> String {
    format!(
        "{}{}",
        endpoint_params_name(method, getter_name),
        upper_camel(location)
    )
}

fn status_field_name(status: u16) -> String {
    format!("s{status}")
}

/// Adds Dart class declaration for object schema.
///
/// Example:
/// `class User { final String id; const User({required this.id}); }`
fn add_object_model_class(
    out: &mut String,
    class_name: &str,
    object: &ObjectType,
    identifiers: &BTreeMap<String, String>,
) {
    let required: BTreeSet<&str> = object
        .required
        .as_ref()
        .map(|items| items.iter().map(String::as_str).collect())
        .unwrap_or_default();

    let mut used_fields = HashSet::new();
    let mut fields: Vec<(String, String, bool, Option<String>)> = Vec::new();
    for (prop_name, prop_schema) in &object.properties {
        let mut field_name = sanitize_dart_field_name(prop_name);
        let mut suffix = 2usize;
        while used_fields.contains(&field_name) {
            field_name = format!("{field_name}{suffix}");
            suffix += 1;
        }
        used_fields.insert(field_name.clone());

        let mut field_type = typing::schema_type(prop_schema, identifiers);
        let is_required = required.contains(prop_name.as_str());
        if !is_required && !field_type.ends_with('?') {
            field_type.push('?');
        }

        let rename_comment = if field_name != *prop_name {
            Some(prop_name.clone())
        } else {
            None
        };
        fields.push((field_name, field_type, is_required, rename_comment));
    }

    out.push_str(&format!("class {class_name} {{\n"));
    for (field_name, field_type, _, original_name) in &fields {
        if let Some(original_name) = original_name {
            out.push_str(&format!(
                "  // Original JSON key: {}\n",
                format::quote(original_name)
            ));
        }
        out.push_str(&format!("  final {field_type} {field_name};\n"));
    }

    out.push('\n');
    if fields.is_empty() {
        out.push_str(&format!("  const {class_name}();\n"));
    } else {
        out.push_str(&format!("  const {class_name}({{\n"));
        for (field_name, _, is_required, _) in &fields {
            if *is_required {
                out.push_str(&format!("    required this.{field_name},\n"));
            } else {
                out.push_str(&format!("    this.{field_name},\n"));
            }
        }
        out.push_str("  });\n");
    }
    out.push_str("}\n");
}

/// Adds Dart enum declaration for string enum schema values.
///
/// Example:
/// `enum Status { active('active'), blocked('blocked'); ... }`
fn add_string_enum_model(out: &mut String, enum_name: &str, values: &[Value]) -> bool {
    let mut cases: Vec<(String, String)> = Vec::new();
    let mut used_names = HashSet::new();

    for value in values {
        let Value::String(raw) = value else {
            continue;
        };

        let mut case_name = sanitize_enum_case_name(raw);
        if case_name.is_empty() {
            continue;
        }

        if is_dart_keyword(&case_name) {
            case_name.push_str("Value");
        }

        let base = case_name.clone();
        let mut n = 2usize;
        while used_names.contains(&case_name) {
            case_name = format!("{base}{n}");
            n += 1;
        }
        used_names.insert(case_name.clone());
        cases.push((case_name, raw.clone()));
    }

    if cases.is_empty() {
        return false;
    }

    out.push_str(&format!("enum {enum_name} {{\n"));
    for (case_name, raw) in &cases {
        out.push_str(&format!("  {case_name}({}),\n", format::quote(raw)));
    }
    out.push_str("  ;\n\n");
    out.push_str("  final String value;\n");
    out.push_str(&format!("  const {enum_name}(this.value);\n"));
    out.push_str("}\n");

    true
}

fn sanitize_enum_case_name(value: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();

    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            current.push(ch);
            continue;
        }
        if !current.is_empty() {
            parts.push(current);
            current = String::new();
        }
    }

    if !current.is_empty() {
        parts.push(current);
    }
    if parts.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    for (idx, part) in parts.into_iter().enumerate() {
        let mut chars = part.chars();
        let Some(first) = chars.next() else {
            continue;
        };
        if idx == 0 {
            out.push(first.to_ascii_lowercase());
        } else {
            out.push(first.to_ascii_uppercase());
        }
        out.extend(chars);
    }

    if out
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        out = format!("v{out}");
    }

    out
}

fn sanitize_dart_field_name(value: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();

    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            current.push(ch);
            continue;
        }
        if !current.is_empty() {
            parts.push(current);
            current = String::new();
        }
    }

    if !current.is_empty() {
        parts.push(current);
    }

    if parts.is_empty() {
        return "field".to_string();
    }

    let mut out = String::new();
    for (idx, part) in parts.into_iter().enumerate() {
        let mut chars = part.chars();
        let Some(first) = chars.next() else {
            continue;
        };

        if idx == 0 {
            out.push(first.to_ascii_lowercase());
        } else {
            out.push(first.to_ascii_uppercase());
        }
        out.extend(chars);
    }

    if out
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        out = format!("field{out}");
    }

    let without_private_prefix = out.trim_start_matches('_');
    if without_private_prefix.is_empty() {
        out = "field".to_string();
    } else if without_private_prefix != out {
        out = without_private_prefix.to_string();
    }

    if is_dart_keyword(&out) {
        return format!("{out}Field");
    }

    out
}

fn ensure_nullable_type(ty: &str) -> String {
    if ty.ends_with('?') {
        ty.to_string()
    } else {
        format!("{ty}?")
    }
}

fn type_literal_expr(ty: &str) -> String {
    ty.strip_suffix('?').unwrap_or(ty).to_string()
}

fn is_dart_keyword(value: &str) -> bool {
    matches!(
        value,
        "abstract"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "base"
            | "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "covariant"
            | "default"
            | "deferred"
            | "do"
            | "dynamic"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "extension"
            | "external"
            | "factory"
            | "false"
            | "final"
            | "finally"
            | "for"
            | "function"
            | "get"
            | "hide"
            | "if"
            | "implements"
            | "import"
            | "in"
            | "interface"
            | "is"
            | "late"
            | "library"
            | "mixin"
            | "new"
            | "null"
            | "on"
            | "operator"
            | "part"
            | "required"
            | "rethrow"
            | "return"
            | "sealed"
            | "set"
            | "show"
            | "static"
            | "super"
            | "switch"
            | "sync"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "type"
            | "typedef"
            | "var"
            | "void"
            | "when"
            | "while"
            | "with"
            | "yield"
    )
}

fn build_schema_getter_names(
    model_names: &BTreeSet<String>,
    identifiers: &BTreeMap<String, String>,
) -> BTreeMap<String, String> {
    let mut used = HashSet::new();
    let mut result = BTreeMap::new();

    for model_name in model_names {
        let ident = identifiers
            .get(model_name)
            .expect("type identifier must exist for each model name");
        let mut chars = ident.chars();
        let Some(first) = chars.next() else {
            continue;
        };
        let base = format!(
            "{}{}",
            first.to_ascii_lowercase(),
            chars.collect::<String>()
        );

        let base = if is_dart_keyword(&base) {
            format!("{base}Schema")
        } else {
            base
        };
        let mut candidate = base.clone();

        let mut n = 2usize;
        while used.contains(&candidate) {
            candidate = format!("{base}{n}");
            n += 1;
        }

        used.insert(candidate.clone());
        result.insert(model_name.clone(), candidate);
    }

    result
}

/// Groups parsed requests by HTTP method and then by path for deterministic output.
fn collect_methods(requests: &[Request]) -> BTreeMap<String, BTreeMap<String, &Request>> {
    let mut methods: BTreeMap<String, BTreeMap<String, &Request>> = BTreeMap::new();
    for req in requests {
        methods
            .entry(req.method.to_lowercase())
            .or_default()
            .insert(req.path.clone(), req);
    }
    methods
}

/// Builds a stable method class name from an HTTP method token.
fn method_class_name(method: &str) -> String {
    format!("Endpoints{}", upper_camel(method))
}

/// Converts an arbitrary token to UpperCamelCase.
fn upper_camel(value: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;

    for ch in value.chars() {
        if !ch.is_ascii_alphanumeric() {
            next_upper = true;
            continue;
        }

        if next_upper {
            out.push(ch.to_ascii_uppercase());
            next_upper = false;
            continue;
        }

        out.push(ch);
    }

    if out.is_empty() {
        "Value".to_string()
    } else {
        out
    }
}

/// Builds stable getter names for each endpoint path in a method group.
fn build_endpoint_getter_names(path_map: &BTreeMap<String, &Request>) -> BTreeMap<String, String> {
    let mut used = HashSet::new();
    let mut result = BTreeMap::new();

    for path in path_map.keys() {
        let base = sanitize_endpoint_getter_name(path);
        let mut candidate = base.clone();
        let mut n = 2usize;

        while used.contains(&candidate) {
            candidate = format!("{base}{n}");
            n += 1;
        }

        used.insert(candidate.clone());
        result.insert(path.clone(), candidate);
    }

    result
}

/// Sanitizes an endpoint path into a lowerCamelCase getter name.
fn sanitize_endpoint_getter_name(path: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();

    for ch in path.chars() {
        if ch.is_ascii_alphanumeric() {
            current.push(ch);
            continue;
        }

        if !current.is_empty() {
            parts.push(current);
            current = String::new();
        }
    }

    if !current.is_empty() {
        parts.push(current);
    }

    if parts.is_empty() {
        return "root".to_string();
    }

    let mut out = String::new();
    for (idx, part) in parts.into_iter().enumerate() {
        let mut chars = part.chars();
        let Some(first) = chars.next() else {
            continue;
        };

        if idx == 0 {
            out.push(first.to_ascii_lowercase());
        } else {
            out.push(first.to_ascii_uppercase());
        }

        out.extend(chars);
    }

    if out
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        out = format!("endpoint{out}");
    }

    match out.as_str() {
        "class" | "enum" | "switch" | "case" | "default" | "get" | "set" | "static" | "void"
        | "final" | "const" => format!("{out}Endpoint"),
        _ => out,
    }
}
